#!/usr/bin/env python3
P='w'
O='input'
E='rb'
N=exit
M=len
J='js'
I='css'
H='.'
G=print
A=open
import os,requests as C
def K(path_to_css_file):
	D=path_to_css_file;F='https://cssminifier.com/raw'
	with A(D,E)as B:G={O:B.read()}
	H=C.post(F,data=G)
	with A(D[:-4]+'.min.css',P)as B:B.write(H.text)
def L(path_to_js_file):
	D=path_to_js_file;F='https://javascript-minifier.com/raw'
	with A(D,E)as B:G={O:B.read()}
	H=C.post(F,data=G)
	with A(D[:-3]+'.min.js',P)as B:B.write(H.text)
def F(list_of_files,directory=H):
	C='/';B=directory;D=[];E=[]
	for A in list_of_files:
		if'.css'in A:yield(I,B+C+A)
		elif'.js'in A:yield(J,B+C+A)
		else:continue
def B(directory=[H]):
	G('started minifying');C=[];D=[]
	for O in directory:
		for E in os.walk(O):
			if E[0]==H:
				for (B,A) in F(E[2]):
					if'.min.'in A:continue
					if B==I:D.append(A)
					elif B==J:C.append(A)
			else:
				for (B,A) in F(E[2],E[0]):
					if'.min'in A:continue
					if B==I:D.append(A)
					elif B==J:C.append(A)
	if M(C)==0 and M(D)==0:G('not found specified files((\nexiting...');N()
	for P in D:K(P)
	for Q in C:L(Q)
	G('all found files (css and js) were minified!!!');N()
if __name__=='__main__':B()
